### ISSUE TITLE
add app icon

### ISSUE THREAD

**Issue by samcooley** [h-be/acorn-release#2]
Looks like requires separate approaches for Linux, macOS, and Windows, by setting `icon` during `mainWindow = new BrowserWindow` in `function createWindow()` of `main.js`.

**Comment by Connoropolous** [comment]
@pegahvaezi I'm going to assign this one to you for now, in terms of delivering icon images, then I can set them up.

**Comment by samcooley** [comment]
for Electron should be this: https://www.electron.build/icons
