### ISSUE TITLE
unable to join existing project

### ISSUE THREAD

**Issue by samcooley** [h-be/acorn-release#20]
**Describe the bug**
After entering a project secret and pressing Join button, button turns to Validating with spinning acorn seemingly indefinitely.  

**To Reproduce**
1. Go to 'Join existing project'
2. Enter project secret
3. Press on 'Join'
4. Validating appears with spinning acorn

**Expected behavior**
Expected existing project to be added to list of projects.

**Screenshots**
![Screenshot 2020-03-28 at 00 23 26](https://user-images.githubusercontent.com/1519349/77810848-04bba380-7097-11ea-9b54-3d4700edd0fa.png)
![Screenshot 2020-03-28 at 00 26 30](https://user-images.githubusercontent.com/1519349/77810849-05ecd080-7097-11ea-9c79-490413a53101.png)
![Screenshot 2020-03-28 at 00 26 39](https://user-images.githubusercontent.com/1519349/77810850-06856700-7097-11ea-9c43-2b24909b394b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu (Xfce 4.12)
 - Browser: N/A (Electron app)
 - Version: Acorn v0.3.1

**Additional context**
Testing first known Linux build of this version.

**Comment by Connoropolous** [comment]
https://github.com/h-be/acorn-release/releases/tag/v0.3.3
